#set deploy

spring.profiles: local
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5434/DATA
    username: smartcity_data
    password: dpsxndpa
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  kafka:
    bootstrap-servers: 1.1.1.1:9092
    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
    healthcheck:
      enabled: true
      
smartcity:
  # smartcity datacore - data service broker 서버URL
  datacore:
    server: http://1.1.1.1:49082
  # smartcity datacore - data manager 서버URL
  datamanager:
    server: http://1.1.1.1:49080
  # 인증인가 서버URL
  auth:
    server: http://1.1.1.1:30117
  # 현재 모듈(dataset-provider) 의 외부접속 가능한 공개IP주소 (data service broker 서버로부터 subscription 의 데이터 수신(HTTP통신) 받기위함)
  dataset-provider-public-ip : 1.1.1.1:18899

file:
  #파일첨부 저장경로
  upload-path: /opt/smartcity
---
spring.profiles: dev
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5434/DATA
    username: smartcity_data
    password: dpsxndpa
    hikari:
      maximum-pool-size: 4
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  kafka:
    bootstrap-servers: 1.1.1.1:9092
    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://1.1.1.1:9761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    ip-address: 1.1.1.1
    
smartcity:
  # smartcity datacore - data service broker 서버URL
  datacore:
    server: http://1.1.1.1:49082
  # smartcity datacore - data manager 서버URL
  datamanager:
    server: http://1.1.1.1:49080
  # 인증인가 서버URL
  auth:
    server: http://1.1.1.1:30117
  # 현재 모듈(dataset-provider) 의 외부접속 가능한 공개IP주소 (data service broker 서버로부터 subscription 의 데이터 수신(HTTP통신) 받기위함)
  dataset-provider-public-ip : 1.1.1.1:18899

file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity    
---
spring.profiles: test
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5432/DATA
    username: smartcity_data
    password: dpsxndpa
    hikari:
      maximum-pool-size: 400
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      
  kafka:
    bootstrap-servers: k1:9092, k2:9092, k3:9092
    auth:
      user_id: dataservice
      user_pw: dataservice!123    
      
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://1.1.1.1:8888/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    ip-address: 1.1.1.1

smartcity:
  # smartcity datacore - data service broker 서버URL
  datacore:
    server: http://1.1.1.1:8082
  # smartcity datacore - data manager 서버URL
  datamanager:
    server: http://1.1.1.1:8080
  # 인증인가 서버URL
  auth:
    server: http://1.1.1.1:30000
  # 현재 모듈(dataset-provider) 의 외부접속 가능한 공개IP주소 (data service broker 서버로부터 subscription 의 데이터 수신(HTTP통신) 받기위함)
  dataset-provider-public-ip : 1.1.1.1:18899

file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity
