#set deploy

spring.profiles: local
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5433/PORTAL
    username: smartcity_portal
    password: dpsxndpa
    hikari:
      maximum-pool-size: 4
  kafka:
    bootstrap-servers: 1.1.1.1:9092
    auth:
      # Kafka 연결 인증 활성화여부
      enabled: false
    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://1.1.1.1:9761/eureka/
    healthcheck:
      enabled: false

smartcity:
  # 인증인가서버(사용자용 서버) URL
  auth:
    server: http://1.1.1.1:30117

file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity
---
spring.profiles: dev
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5433/PORTAL
    username: smartcity_portal
    password: dpsxndpa
    hikari:
      maximum-pool-size: 4
  kafka:
    bootstrap-servers: 1.1.1.1:9092
    auth:
      # Kafka 연결 인증 활성화여부
      enabled: false
    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://1.1.1.1:9761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    ip-address: 1.1.1.1

smartcity:
  # 인증인가서버(사용자용 서버) URL
  auth:
    server: http://1.1.1.1:30117
    
file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity
---
spring.profiles: test
spring:
  datasource:
    url: jdbc:postgresql://1.1.1.1:5432/portal
    username: smartcity_portal
    password: dpsxndpa
    hikari:
      maximum-pool-size: 4
  kafka:
    bootstrap-servers: k1:9092, k2:9092, k3:9092
    auth:
      # Kafka 연결 인증 활성화여부
      enabled: true
      user_id: dataservice
      user_pw: dataservice!123    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://1.1.1.1:8888/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    ip-address: 1.1.1.1
    
smartcity:
  # 인증인가서버(사용자용 서버) URL
  auth:
    server: http://1.1.1.1:30000
    
file:
  # 첨부파일 저장경로
  upload-path: /opt/smartcity    
